apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: frontend
      tier: frontend
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: hanvihanshith/frontend:v1
        imagePullPolicy: Always
        ports: 
        - name: liveness-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: 80 
          failureThreshold: 1
          periodSeconds: 30
---
apiVersion: v1 
kind: Service
metadata: 
  name: frontend
  namespace: safety
spec:
  type: LoadBalancer
  selector:
    project: safety
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 ## services port
      targetPort: 80 ## container port