apiVersion: v1
kind: ConfigMap
metadata: 
  name: payment
  namespace: safety
data: 
 
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: payment
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: payment
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: payment
      tier: backend
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: payment
        tier: backend
    spec:
      containers:
      - name: payment
        image: hanvihanshith/payment:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment
        ports: 
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 30
---
apiVersion: v1 
kind: Service
metadata: 
  name: payment
  namespace: safety
spec:
  selector:
    project: safety
    component: payment
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 ## services port
      targetPort: 8080 ## container port