apiVersion: v1
kind: ConfigMap
metadata: 
  name: cart
  namespace: safety
data: 
 REDIS_HOST: "redis"
 CATALOGUE_HOST: "catalogue"
 CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cart
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: cart
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: cart
      tier: backend
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: hanvihanshith/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart
        ports: 
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 25
---
apiVersion: v1 
kind: Service
metadata: 
  name: cart
  namespace: safety
spec:
  selector:
    project: safety
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 ## services port
      targetPort: 8080 ## container port