apiVersion: v1
kind: ConfigMap
metadata: 
  name: shipping
  namespace: safety
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shipping
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: shipping
      tier: backend
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: hanvihanshith/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports: 
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 25
---
apiVersion: v1 
kind: Service
metadata: 
  name: shipping
  namespace: safety
spec:
  selector:
    project: safety
    component: shipping
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 ## services port
      targetPort: 8080 ## container port