apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: mysql
      tier: db
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: hanvihanshith/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1 
kind: Service
metadata: 
  name: mysql
  namespace: safety
spec:
  selector:
    project: safety
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 ## services port
      targetPort: 3306 ## container port