apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql
  namespace: safety
data: 
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: mysql
      tier: db
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: mysql
        tier: db
    spec:
      serviceAccount: secret-reader-sa
      initContainers:
      - name: fetch-secret
        image: amazon/aws-cli
        command:
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id safety/dev-1/mysql-password --query 'SecretString' --output text | jq -r '.["mysql-password"]' > /tmp/mysql-root-password.txt
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp
      containers:
      - name: mysql
        image: hanvihanshith/mysql:v2
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: mysql-secret
          mountPath: /tmp

      volumes:
       - name: mysql-config
         configMap:
          name: mysql 
       - name: mysql-secret

