apiVersion: apps/v1 
kind: Deployment
metadata:
  name: catalogue
  namespace: safety
# these are deployment labels
  labels:
    project: safety
    component: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: safety
      component: catalogue
      tier: backend
    # pod definitdion
  template: 
    metadata:
      labels:
        project: safety
        component: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: hanvihanshith/catalogue:v1
        ports: 
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health 
            port: 8080  
          failureThreshold: 1
          periodSeconds: 20
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue
  namespace: safety
spec:
  selector:
    project: safety
    component: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 ## services port
      targetPort: 8080 ## container port